###########################
# _____ __  __ _   ___  __#
#|_   _|  \/  | | | \ \/ /#
#  | | | |\/| | | | |\  / #
#  | | | |  | | |_| |/  \ #
#  |_| |_|  |_|\___//_/\_\#
###########################

#=================
#  TPM BOOTSTRAP
#=================
set-environment -gF TMUX_PLUGIN_MANAGER_PATH '#{HOME}/.local/share/tmux/plugins/'

if 'test ! -d "${TMUX_PLUGIN_MANAGER_PATH}/tpm"' {
  run 'mkdir -p "${TMUX_PLUGIN_MANAGER_PATH}"'
  run 'git clone https://github.com/tmux-plugins/tpm "${TMUX_PLUGIN_MANAGER_PATH}/tpm"'
  run '${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin/install_plugins'
}

#=================
#  CORE OPTIONS
#=================
set-option -g default-shell /bin/zsh
set -g default-terminal 'tmux-256color'
set -ag terminal-overrides ',xterm-256color*:RGB'

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g focus-events on
set -g mouse on
set -g allow-passthrough on
set -g escape-time 0
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on
set -g allow-rename off
set -g status-interval 5

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

#=================
#  PLUGINS
#=================
# Basic
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
# Themeing
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
# Utils
set -g @plugin 'alexwforsythe/tmux-which-key'  # prefix + space
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
# Tools
set -g @plugin 'omerxx/tmux-sessionx'          # prefix + o

#=================
#  PLUGIN OPTIONS
#=================
# FZF
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

#=================
#  CATPPUCCIN THEME
#=================
set -g @catppuccin_flavor 'frappe'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_default_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_date_time_text '%d.%m. %H:%M'

set -g @catppuccin_status_module_text_bg '#{E:@thm_surface_0}'
set -g @catppuccin_window_current_color '#{E:@thm_overlay_2}'

# source the plugin here
run '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/catppuccin.tmux'

#=================
#  MODULES
#=================
#Custom
source -F '#{HOME}/.dotfiles/tmux/custom_modules/ctp_cpu.conf'

set -g allow-rename off
set -g status-position top
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
# Left
set -g status-left '#{E:@catppuccin_status_session} '
# Right
set -gF status-right '#{E:@catppuccin_status_ctp_cpu}'
if 'test -r /sys/class/power_supply/BAT*' {
  set -agF status-right '#{E:@catppuccin_status_battery}'
}
set -ag status-right '#{E:@catppuccin_status_date_time}'

#=================
#  KEYBINDINGS
#=================
set -g prefix M-space
set-window-option -g mode-keys vi
setw -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

unbind r
bind r source-file "~/.dotfiles/tmux/tmux.conf" \; display-message "🔁 Tmux config reloaded!"

bind -n S-Left  previous-window
bind -n S-Right next-window
bind -n M-H previous-window
bind -n M-L next-window

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#=================
#  TPM / FINAL
#=================
run '#{TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm'
